// Generated by CoffeeScript 1.4.0
(function() {
  var LinearCongruential;

  LinearCongruential = (function() {

    function LinearCongruential(seed) {
      this.seed = seed != null ? seed : 1;
    }

    LinearCongruential.prototype.plantSeed = function(seed) {
      this.seed = seed != null ? seed : 1;
    };

    LinearCongruential.prototype.get = function() {
      var m, p, q, tmp;
      tmp = this.seed;
      q = tmp;
      q = q << 1;
      p = tmp << 32;
      m = p + q;
      if (m & 0x80000000) {
        m = m & 0x7fffffff;
        m++;
      }
      this.seed = m;
      return m / 0x80000000;
    };

    return LinearCongruential;

  })();

  module.exports = LinearCongruential;

}).call(this);
