// Generated by CoffeeScript 1.3.3
(function() {
  var NoRandom;

  NoRandom = (function() {

    function NoRandom(n) {
      this.n = n;
    }

    NoRandom.prototype.get = function() {
      return this.n;
    };

    return NoRandom;

  })();

  module.exports = NoRandom;

}).call(this);
